namespace FFX.EditorPanels.Debug
{
    public enum DebugFlags
    {
        EnemyInvincible,
        PartyInvincible,
        EnemyInput,
        Unknown1,
        FreeCamera,
        Unknown2,
        Unknown3,
        Unknown4,
        Unknown5,
        Unknown6,
        Unknown7,
        Unknown8,
        Unknown9,
        Unknown10,
        Unknown11,
        Unknown12,
        Unknown13,
        Unknown14,
        Unknown15,
        Unknown16,
        AlwaysOverdrive,
        AlwaysCritical,
        AlwaysDeal1,
        AlwaysDeal10000,
        AlwaysDeal99999,
        AlwaysRareDrop,
        Ap100X,
        Gil100X,
        Unknown18,
        PermanentSensor,
        Unknown19,
        UnknownHangGame
    }
}
